### ISSUE TITLE
deploy fails

### ISSUE THREAD

**Issue by WinstonHartnett** [robotpy/robotpy-installer#45]
We're getting an error preventing us from deploying. All of the latest packages should be installed.

```
source venv/bin/activate && python robot.py deploy
  16:51:44:288 INFO    : wpilib              : WPILib version 2020.2.2.8
  16:51:44:288 INFO    : wpilib              : HAL version 2020.2.2.0
  16:51:44:288 INFO    : wpilib              : Running with simulated HAL.
  16:51:44:288 INFO    : faulthandler        : registered SIGUSR2 for PID 13059
  16:51:44:289 INFO    : robotpy.installer   : Finding robot for team 6672
  16:51:44:299 INFO    : robotpy.installer   : -> Robot is at 10.66.72.2
  16:51:44:299 INFO    : robotpy.installer   : Connecting to robot via SSH at 10.66.72.2
  16:51:44:714 INFO    : paramiko.transport  : Connected (version 2.0, client OpenSSH_7.6)
  16:51:45:233 INFO    : paramiko.transport  : Auth banner: b'NI Linux Real-Time (run mode)\n\nLog in with your NI-Auth credentials.\n\n'
  16:51:45:233 INFO    : paramiko.transport  : Authentication (password) successful!
  WPILib version on robot is 2020.2.2.8
  Traceback (most recent call last):
    File "robot.py", line 21, in <module>
      run(Green)
    File "/home/winston/Code/Python/2020-Green/venv/lib/python3.8/site-packages/wpilib/_impl/main.py", line 186, in run
    retval = options.cmdobj.run(options, robot_class, **kwargs)
  File "/home/winston/Code/Python/2020-Green/venv/lib/python3.8/site-packages/pyfrc/mains/cli_deploy.py", line 258, in run
    controller.ssh_exec_commands(sshcmd, True)
  File "/home/winston/Code/Python/2020-Green/venv/lib/python3.8/site-packages/robotpy_installer/sshcontroller.py", line 57, in ssh_exec_commands
    for line in iter(stderr.readLine, ""):
AttributeError: 'ChannelStderrFile' object has no attribute 'readLine'
```

**Comment by auscompgeek** [comment]
Sorry about that. If you install the latest version of robotpy-installer deploys should work properly now.
